site_name: "DigSam's ML Hub"  # Change the name as needed
theme:
  name: "material"  # Use the Material theme for better styling
  palette:
    scheme: slate  # Dark mode by default
    primary: indigo
    accent: pink
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.instant   # Instant navigation
    - navigation.tabs      # Tabbed navigation for better organisation
    - navigation.top       # Include a atop navigation bar
    - navigation.expand    # Expand all sections by default
    - toc.integrate        # Integrate table of contents into the side bar
    - search.highlight     # Highlight search terms
    - search.share         # Enable sharing search results
  palette:
    - scheme: slate # Dark mode (or use "default" for light mode)
      primary: blue
      accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono

nav:  # Define navigation structure
  - Home: index.md
  - Training:
      - Schedule: training/schedule.md
      - Tutorials: training/tutorials.md
  - Events:
      - Workshops: events/workshops.md
      - Presentations: events/presentations.md
  - Resources:
      - Tools: resources/tools.md
  - About: about.md

# Add plugins if needed
plugins:
  - search
  - markdownextradata
  - macros

# Add extra css from stylesheets/extra.css
extra_css:
  - stylesheets/extra.css
